export const tasksData = [
  {
    id: 1,
    title: "Crear porfolio",
    description:
      "Debo crear un porfolio para poder aplicar a empleas de programacion",
    createdAt: new Date(),
    deliverIt: new Date(),
    status: "Pendiente",
    priority: "Medio",
    quickAccess: true,
  },
  {
    id: 2,
    title: "TaskCore",
    description: "Terminar el poryecto TaskCore para agregar a mi portfolio",
    createdAt: new Date(),
    deliverIt: new Date(),
    status: "En progreso",
    priority: "Alto",
    quickAccess: false,
  },
  {
    id: 3,
    title: "MKM tarea",
    description: "otra descripcion para la tarea",
    createdAt: new Date(),
    deliverIt: new Date(),
    status: "Completado",
    priority: "Alto",
    quickAccess: false,
  },
  {
    id: 4,
    title: "Cbtra tarea",
    description: "otra descripcion para la tarea",
    createdAt: new Date(),
    deliverIt: new Date(),
    status: "Completado",
    priority: "Alto",
    quickAccess: true,
  },
  {
    id: 5,
    title: "BCtra tarea",
    description: "otra descripcion para la tarea",
    createdAt: new Date(),
    deliverIt: new Date(),
    status: "Completado",
    priority: "Bajo",
    quickAccess: false,
  },
  {
    id: 6,
    title: "Abtra tarea",
    description: "otra descripcion para la tarea",
    createdAt: new Date(),
    deliverIt: new Date(),
    status: "Pendiente",
    priority: "Alto",
    quickAccess: true,
  },
  {
    id: 7,
    title: "XZtra tarea",
    description: "otra descripcion para la tarea",
    createdAt: new Date(),
    deliverIt: new Date(),
    status: "Pendiente",
    priority: "Alto",
    quickAccess: true,
  },
  {
    id: 8,
    title: "KLtra tarea",
    description: "otra descripcion para la tarea",
    createdAt: new Date(),
    deliverIt: new Date(),
    status: "Pendiente",
    priority: "Alto",
    quickAccess: true,
  },
  {
    id: 9,
    title: "NIKtra tarea",
    description: "otra descripcion para la tarea",
    createdAt: new Date(),
    deliverIt: new Date(),
    status: "Pendiente",
    priority: "Alto",
    quickAccess: true,
  },
];
