import { auth } from "@/auth";
import { Navbar } from "@/components/navbar";
import type { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "TaskCore",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  if (!session || !session?.user) {
    redirect("/auth/login");
  }

  return (
    <>
      <Navbar />
      {children}
    </>
  );
}
